# Before your start:

    Read the README.md file
    Comment as much as you can and use the resources (README.md file)
    Happy learning!

In this exercise, we  will generate random numbers from the continuous disributions we learned in the lesson. There are two ways to generate random numbers:

1. Using the numpy library 
1. using the Scipy library 

Use either or both of the lbraries in this exercise.

## Uniform Distribution

To generate uniform random numbers between any two given values using scipy, we can either use the following code or the code that we have
discussed in class:

In [3]:
from scipy.stats import uniform
x = uniform.rvs(size=10)
a = 2
b = 3
randoms  = a + (b-a) * x
randoms



array([2.09244978, 2.16685414, 2.91982228, 2.2358181 , 2.67599049,
       2.70727377, 2.74658809, 2.58978826, 2.1024181 , 2.78413564])

**Your task:**

1. Based on the code above, write a function that generates uniformly distributed random numbers. There are several requirements for your function:
    * It should accept 3 parameters: 
        * `bottom` - the lower boundary of the generated numbers
        * `ceiling` - the upper boundary of the generated numbers
        * `count` - how many numbers to generate
    * It should return an array of uniformly distributed random numbers

1. Call your function with 2 sets of params below:
    * bottom=10, ceiling=15, count=100
    * bottom=10, ceiling=60, count=1,000

1. Plot the uniform distributions generated above using histograms, where x axis is the value and y axis is the count. Let the histogram's number of bins be 10.

Your output should look like below:

![uniform distribution](ud.png)

In [13]:
def uniforms(low,high,count):
    x = uniform.rvs(size=count)
    a = low
    b = high
    randoms = a + (b-a) * x
    return randoms

uniforms(2,3,10)

array([2.55932728, 2.67440612, 2.90486656, 2.33440043, 2.576434  ,
       2.218245  , 2.60450871, 2.06593574, 2.88587113, 2.88987097])

How are the two distributions different?

In [ ]:
# Only the random numbers are different. But the functions return the same type of answers

## Normal Distribution

1. In the same way in the Uniform Distribution challenge, write a function that generates normally distributed random numbers.
1. Generate 1,000 normally distributed numbers with the average of 10 and standard deviation of 1
1. Generate 1,000 normally distributed numbers with the average of 10 and standard deviation of 50
2. Plot the distributions of the data generated.

Expected output:

![normal distribution](nd.png)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import math

# print(np.random.normal(5.1, 1.6, 100))

def normals(mean, var, size):
    
#     mu = 0
#     sigma = math.sqrt(var)
#     x = np.linspace(mu - 3*sigma, mu + 3*sigma, size)
#     plt.plot(x, stats.norm.pdf(mean,mu,var))
    return np.random.normal(mean, var, size)

normals(10, 1, 1000)
normals(10, 50, 1000)



    

array([ 1.67210681e+01,  6.95153635e+01,  2.55372444e+01,  1.48733657e+02,
        1.08573909e+00,  4.89546224e+01,  7.92186082e+01, -2.47226750e+01,
        5.95611198e+01,  2.50517684e+01,  8.05158551e+01,  7.08274060e+01,
       -3.12295526e-01, -8.58860737e+00, -1.02736642e+02,  3.34581215e+01,
        1.25178130e+02, -4.16471585e+01, -4.60422426e+01,  1.06694963e+02,
        3.22358943e+01, -2.51761220e+01, -5.03106435e+00, -6.68925056e+01,
       -3.47999487e+01,  2.29949205e+01,  2.27945179e+01,  4.37425220e-02,
       -2.33442944e+01,  9.59193475e+00, -1.72644383e+01, -2.12992284e+01,
       -4.11641456e+01,  8.89312586e+01,  2.16524372e+01, -3.91833964e+01,
        1.61171784e+00, -4.21578197e+00,  5.84338275e+01, -6.55071632e+01,
       -2.93962810e+01, -6.15177183e+01, -2.63445099e+01, -7.63332941e+01,
        1.37959128e+01,  1.11492946e+01, -9.59371711e+01, -3.81802851e+01,
        8.21859769e+01,  9.94659462e+01, -3.11602599e+01,  1.96654873e+01,
        6.43327549e+01, -

How are the two distributions different?

In [ ]:
# your answer below

## Normal Distribution of Real Data

In this challenge we are going to take a look the real data. We will use vehicles.csv file for this exercise

First import vehicles.csv.
Then plot the histograms for the following variables:

1. Fuel Barrels/Year

In [ ]:
# your code here

2. CO2 Emission Grams/Mile 

In [ ]:
# your code here

3. Combined MPG

In [ ]:
# your code here

Which one(s) of the variables are nearly normally distributed? How do you know?

In [ ]:
# your answer here

## Exponential Distribution

1. Using `numpy.random.exponential`, create a function that returns a list of numbers exponentially distributed with the mean of 10. 

1. Use the function to generate two number sequences with the size of 1 and 100.

1. Plot the distributions as histograms with the nubmer of bins as 100.

Your output should look like below:

![exponential distribution](ed.png)

In [ ]:
# your code here

How are the two distributions different?

In [ ]:
# your answer here

## Exponential Distribution of Real Data

Suppose that the amount of time one spends in a bank is exponentially distributed with mean as 10 minutes (i.e. λ = 1/10). What is the probability that a customer will spend less than fifteen minutes in the bank? 

Write a code in python to solve this problem

In [ ]:
# your answer here
# Hint: This is same as saying P(x<15)

What is the probability that the customer will spend more than 15 minutes

In [ ]:
# your answer here