In [ ]:
#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

In [ ]:
#2. Print the NUMPY version and the configuration.

In [2]:
print(np.version)
print(np.__version__)

<module 'numpy.version' from 'C:\\Users\\Repairmanmanmanman\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
1.16.2


In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

In [ ]:
#4. Print a.

In [4]:
print(a)

[[[0.22158485 0.04807432 0.0954779  0.57710815 0.18434242]
  [0.65711283 0.90303116 0.37173794 0.26945126 0.77858999]
  [0.82634132 0.7269357  0.32572842 0.85132885 0.53449109]]

 [[0.80131585 0.27133479 0.70580848 0.08138466 0.73523325]
  [0.90460171 0.60729769 0.79632425 0.02129288 0.31126919]
  [0.28643191 0.72780945 0.49201917 0.03838039 0.89128998]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


In [5]:
b = np.full((5,2,3), 1)

In [ ]:
#6. Print b.

In [6]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
if a.size == b.size:
    print("True")

True


In [ ]:
#8. Are you able to add a and b? Why or why not?

In [17]:
#print(np.add(a, b))
#No because while the amount of elements are the same, the length of each is different.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".

In [8]:
c = b.transpose(1,2,0)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [9]:
d = np.add(a,c)
print(d)
#It works because they are now on the same axis.

[[[1.14529952 1.91957958 1.8353386  1.34309002 1.46975901]
  [1.33506067 1.99302888 1.43797516 1.41539194 1.58377439]
  [1.86238729 1.39274062 1.01937436 1.95649351 1.02630257]]

 [[1.79069506 1.81151549 1.63785293 1.27010148 1.03132061]
  [1.86006589 1.99647372 1.21702181 1.17466725 1.85958838]
  [1.97480268 1.70165186 1.72857595 1.79858948 1.03733132]]]


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [10]:
print(a)
print(d)
#Everything in D is equal to everything in A plus 1.

[[[0.14529952 0.91957958 0.8353386  0.34309002 0.46975901]
  [0.33506067 0.99302888 0.43797516 0.41539194 0.58377439]
  [0.86238729 0.39274062 0.01937436 0.95649351 0.02630257]]

 [[0.79069506 0.81151549 0.63785293 0.27010148 0.03132061]
  [0.86006589 0.99647372 0.21702181 0.17466725 0.85958838]
  [0.97480268 0.70165186 0.72857595 0.79858948 0.03733132]]]
[[[1.14529952 1.91957958 1.8353386  1.34309002 1.46975901]
  [1.33506067 1.99302888 1.43797516 1.41539194 1.58377439]
  [1.86238729 1.39274062 1.01937436 1.95649351 1.02630257]]

 [[1.79069506 1.81151549 1.63785293 1.27010148 1.03132061]
  [1.86006589 1.99647372 1.21702181 1.17466725 1.85958838]
  [1.97480268 1.70165186 1.72857595 1.79858948 1.03733132]]]


In [ ]:
#12. Multiply a and c. Assign the result to e.

In [11]:
e = np.multiply(a,c)
print(e)

[[[0.14529952 0.91957958 0.8353386  0.34309002 0.46975901]
  [0.33506067 0.99302888 0.43797516 0.41539194 0.58377439]
  [0.86238729 0.39274062 0.01937436 0.95649351 0.02630257]]

 [[0.79069506 0.81151549 0.63785293 0.27010148 0.03132061]
  [0.86006589 0.99647372 0.21702181 0.17466725 0.85958838]
  [0.97480268 0.70165186 0.72857595 0.79858948 0.03733132]]]


In [ ]:
#13. Does e equal to a? Why or why not?

In [32]:
#Yes because multiplying anything by 1 changes nothing.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [12]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

1.9964737173233384 1.019374361358449 1.5541950006049052


In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [24]:
f = np.empty((2,3,5))

In [ ]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
"""

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


In [59]:
for idx, line in enumerate(d):
    print(idx)
#     if idx > d_mean and idx < d_max:
#         f[idx] = 75
#     if idx == d_mean:
#         f[idx] = 50
#     if idx == d_min:
#         f[idx] = 0
#     if idx == d_max:
#         f[idx] = 100
# print(f)

0
1


In [47]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
                if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                    f[i][j][k] = 75
                elif d[i][j][k] == d_mean:
                    f[i][j][k] = 50
                elif d[i][j][k] == d_min:
                    f[i][j][k] = 0
                elif d[i][j][k] == d_max:
                    f[i][j][k] = 100
                else:
                    f[i][j][k] = 0
print(f)

[[[  0.  75.  75.   0.   0.]
  [  0.  75.   0.   0.  75.]
  [ 75.   0.   0.  75.   0.]]

 [[ 75.  75.  75.   0.   0.]
  [ 75. 100.   0.   0.  75.]
  [ 75.  75.  75.  75.   0.]]]


In [ ]:
#17. Print d and f. Do you have your expected f?

'''
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
             
Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


In [48]:
print(d)
print(f)

[[[1.14529952 1.91957958 1.8353386  1.34309002 1.46975901]
  [1.33506067 1.99302888 1.43797516 1.41539194 1.58377439]
  [1.86238729 1.39274062 1.01937436 1.95649351 1.02630257]]

 [[1.79069506 1.81151549 1.63785293 1.27010148 1.03132061]
  [1.86006589 1.99647372 1.21702181 1.17466725 1.85958838]
  [1.97480268 1.70165186 1.72857595 1.79858948 1.03733132]]]
[[[  0.  75.  75.   0.   0.]
  [  0.  75.   0.   0.  75.]
  [ 75.   0.   0.  75.   0.]]

 [[ 75.  75.  75.   0.   0.]
  [ 75. 100.   0.   0.  75.]
  [ 75.  75.  75.  75.   0.]]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 

'''
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
'''

In [61]:
g = f.copy().astype(str)

for i in range(len(d)):
   for j in range(len(d[i])):
       for k in range(len(d[i][j])):
           if d[i][j][k] > d_min and d[i][j][k] < d_mean:
               g[i][j][k] ='B'
           elif d[i][j][k]> d_mean and d[i][j][k] <d_max:
               g[i][j][k] = 'D'
           elif d[i][j][k] == d_mean:
               g[i][j][k] ='C'
           elif d[i][j][k] == d_min:
               g[i][j][k]='A'
           elif d[i][j][k] == d_max:
               g[i][j][k]='E'
           else:
               g[i][j][k]=0
   print(g)

[[['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'B' 'A' 'D' 'B']]

 [['75.0' '75.0' '75.0' '0.0' '0.0']
  ['75.0' '100.0' '0.0' '0.0' '75.0']
  ['75.0' '75.0' '75.0' '75.0' '0.0']]]
[[['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'B' 'A' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'B']
  ['D' 'E' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'B']]]
