In [43]:
import numpy as np

print(np.__version__, '\n\n')
print(np.show_config())

1.16.4 


mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rbarr/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/rbarr/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rbarr/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

In [44]:
a = np.random.random((2, 3, 5))
a1 = np.random.rand(2, 3, 5)
a2 = np.random.randint(101, size = (2, 3, 5))
a3 = np.random.random_integers(101, size = (2, 3, 5))
print(a, '\n\n')

[[[0.08383157 0.15257845 0.90432785 0.14107541 0.03438504]
  [0.6719631  0.91465938 0.34543607 0.34345476 0.83993454]
  [0.81383427 0.74416843 0.17506768 0.60011802 0.05803383]]

 [[0.57645127 0.31370629 0.54411758 0.12101357 0.70672101]
  [0.6618312  0.35823685 0.09458892 0.84804599 0.01263161]
  [0.22557192 0.88788844 0.11774078 0.55379225 0.11212975]]] 




C:\Users\rbarr\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 101 + 1) instead
  after removing the cwd from sys.path.


In [45]:
b = np.ones((5, 3, 2), dtype = int)
b1 = np.random.randint(1, 2, size = (5, 3, 2))
print(b, '\n\n')
print(a.size == b.size, '\n\n')
print(a.shape == b.shape, '\n\n')

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]] 


True 


False 




In [46]:
c = b.T
c1 = b.transpose()
c2 = np.transpose(b)
print(c, '\n\n')
print(a.size == c.size, '\n\n')
print(a.shape == c.shape, '\n\n')

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]] 


True 


True 




In [111]:
d = a + c
print(a, '\n\n')
print(d, '\n\n')

[[[0.08383157 0.15257845 0.90432785 0.14107541 0.03438504]
  [0.6719631  0.91465938 0.34543607 0.34345476 0.83993454]
  [0.81383427 0.74416843 0.17506768 0.60011802 0.05803383]]

 [[0.57645127 0.31370629 0.54411758 0.12101357 0.70672101]
  [0.6618312  0.35823685 0.09458892 0.84804599 0.01263161]
  [0.22557192 0.88788844 0.11774078 0.55379225 0.11212975]]] 


[[[1.08383157 1.15257845 1.90432785 1.14107541 1.03438504]
  [1.6719631  1.91465938 1.34543607 1.34345476 1.83993454]
  [1.81383427 1.74416843 1.17506768 1.60011802 1.05803383]]

 [[1.57645127 1.31370629 1.54411758 1.12101357 1.70672101]
  [1.6618312  1.35823685 1.09458892 1.84804599 1.01263161]
  [1.22557192 1.88788844 1.11774078 1.55379225 1.11212975]]] 




In [82]:
e = a * c
print(a, '\n\n')
print(e, '\n\n')
print(np.array_equal(a, e))

[[[0.08383157 0.15257845 0.90432785 0.14107541 0.03438504]
  [0.6719631  0.91465938 0.34543607 0.34345476 0.83993454]
  [0.81383427 0.74416843 0.17506768 0.60011802 0.05803383]]

 [[0.57645127 0.31370629 0.54411758 0.12101357 0.70672101]
  [0.6618312  0.35823685 0.09458892 0.84804599 0.01263161]
  [0.22557192 0.88788844 0.11774078 0.55379225 0.11212975]]] 


[[[0.08383157 0.15257845 0.90432785 0.14107541 0.03438504]
  [0.6719631  0.91465938 0.34543607 0.34345476 0.83993454]
  [0.81383427 0.74416843 0.17506768 0.60011802 0.05803383]]

 [[0.57645127 0.31370629 0.54411758 0.12101357 0.70672101]
  [0.6618312  0.35823685 0.09458892 0.84804599 0.01263161]
  [0.22557192 0.88788844 0.11774078 0.55379225 0.11212975]]] 


True


In [92]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, '\n\n')
print(d_min, '\n\n')
print(d_mean, '\n\n')

1.914659380527626 


1.012631607275837 


1.4319111937592102 




In [115]:
f = d.copy()

f[(f > d_min) & (f < d_mean)] = 25
f[(f > d_mean) & (f < d_max)] = 75
f[f == d_mean] = 50
f[f == d_min] = 0
f[f == d_max] = 100

f1 = d.copy()

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f1[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f1[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f1[i][j][k] = 50   
            elif d[i][j][k] == d_min:
                f1[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f1[i][j][k] = 100
            else:
                f1[i][j][k] = None

print(d, '\n\n')
print(f, '\n\n')
print(f1, '\n\n')

[[[1.08383157 1.15257845 1.90432785 1.14107541 1.03438504]
  [1.6719631  1.91465938 1.34543607 1.34345476 1.83993454]
  [1.81383427 1.74416843 1.17506768 1.60011802 1.05803383]]

 [[1.57645127 1.31370629 1.54411758 1.12101357 1.70672101]
  [1.6618312  1.35823685 1.09458892 1.84804599 1.01263161]
  [1.22557192 1.88788844 1.11774078 1.55379225 1.11212975]]] 


[[[ 25.  25.  75.  25.  25.]
  [ 75. 100.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75.  25.  25.  75.   0.]
  [ 25.  75.  25.  75.  25.]]] 


[[[ 25.  25.  75.  25.  25.]
  [ 75. 100.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75.  25.  25.  75.   0.]
  [ 25.  75.  25.  75.  25.]]] 




In [131]:
g = f.copy().astype(str)

g[f == 0] = 'A'
g[f == 25] = 'B'
g[f == 50] = 'C'
g[f == 75] = 'D'
g[f == 100] = 'E'

g1 = d.copy().astype(str)

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g1[i][j][k] = 'B'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                g1[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                g1[i][j][k] = 'C'   
            elif d[i][j][k] == d_min:
                g1[i][j][k] = 'A'
            elif d[i][j][k] == d_max:
                g1[i][j][k] = 'E'
            else:
                g1[i][j][k] = None

print(d, '\n\n')
print(g, '\n\n')
print(g1, '\n\n')

[[[1.08383157 1.15257845 1.90432785 1.14107541 1.03438504]
  [1.6719631  1.91465938 1.34543607 1.34345476 1.83993454]
  [1.81383427 1.74416843 1.17506768 1.60011802 1.05803383]]

 [[1.57645127 1.31370629 1.54411758 1.12101357 1.70672101]
  [1.6618312  1.35823685 1.09458892 1.84804599 1.01263161]
  [1.22557192 1.88788844 1.11774078 1.55379225 1.11212975]]] 


[[['B' 'B' 'D' 'B' 'B']
  ['D' 'E' 'B' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['D' 'B' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'A']
  ['B' 'D' 'B' 'D' 'B']]] 


[[['B' 'B' 'D' 'B' 'B']
  ['D' 'E' 'B' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['D' 'B' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'A']
  ['B' 'D' 'B' 'D' 'B']]] 


