In [3]:
import numpy as np

print(np.__version__, '\n\n')
print(np.show_config())

1.16.4 


mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rbarr/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/rbarr/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rbarr/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

In [4]:
a = np.random.random((2, 3, 5))
a1 = np.random.rand(2, 3, 5)
a2 = np.random.randint(101, size = (2, 3, 5))
a3 = np.random.random_integers(101, size = (2, 3, 5))
print(a, '\n\n')

[[[0.78880951 0.55957597 0.66695463 0.52644252 0.68868902]
  [0.53564137 0.37914965 0.70407362 0.12872362 0.8455654 ]
  [0.90476228 0.91983747 0.23117976 0.93933524 0.22597083]]

 [[0.79198097 0.67772611 0.73141591 0.26687977 0.69581685]
  [0.2248575  0.26602637 0.08408424 0.84938186 0.94730539]
  [0.87901224 0.20191186 0.63780328 0.51041547 0.46684125]]] 




C:\Users\rbarr\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 101 + 1) instead
  after removing the cwd from sys.path.


In [5]:
b = np.ones((5, 3, 2), dtype = int)
b1 = np.random.randint(1, 2, size = (5, 3, 2))
print(b, '\n\n')
print(a.size == b.size, '\n\n')
print(a.shape == b.shape, '\n\n')

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]] 


True 


False 




In [6]:
c = b.T
c1 = b.transpose()
c2 = np.transpose(b)
print(c, '\n\n')
print(a.size == c.size, '\n\n')
print(a.shape == c.shape, '\n\n')

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]] 


True 


True 




In [7]:
d = a + c
print(a, '\n\n')
print(d, '\n\n')

[[[0.78880951 0.55957597 0.66695463 0.52644252 0.68868902]
  [0.53564137 0.37914965 0.70407362 0.12872362 0.8455654 ]
  [0.90476228 0.91983747 0.23117976 0.93933524 0.22597083]]

 [[0.79198097 0.67772611 0.73141591 0.26687977 0.69581685]
  [0.2248575  0.26602637 0.08408424 0.84938186 0.94730539]
  [0.87901224 0.20191186 0.63780328 0.51041547 0.46684125]]] 


[[[1.78880951 1.55957597 1.66695463 1.52644252 1.68868902]
  [1.53564137 1.37914965 1.70407362 1.12872362 1.8455654 ]
  [1.90476228 1.91983747 1.23117976 1.93933524 1.22597083]]

 [[1.79198097 1.67772611 1.73141591 1.26687977 1.69581685]
  [1.2248575  1.26602637 1.08408424 1.84938186 1.94730539]
  [1.87901224 1.20191186 1.63780328 1.51041547 1.46684125]]] 




In [8]:
e = a * c
print(a, '\n\n')
print(e, '\n\n')
print(np.array_equal(a, e))

[[[0.78880951 0.55957597 0.66695463 0.52644252 0.68868902]
  [0.53564137 0.37914965 0.70407362 0.12872362 0.8455654 ]
  [0.90476228 0.91983747 0.23117976 0.93933524 0.22597083]]

 [[0.79198097 0.67772611 0.73141591 0.26687977 0.69581685]
  [0.2248575  0.26602637 0.08408424 0.84938186 0.94730539]
  [0.87901224 0.20191186 0.63780328 0.51041547 0.46684125]]] 


[[[0.78880951 0.55957597 0.66695463 0.52644252 0.68868902]
  [0.53564137 0.37914965 0.70407362 0.12872362 0.8455654 ]
  [0.90476228 0.91983747 0.23117976 0.93933524 0.22597083]]

 [[0.79198097 0.67772611 0.73141591 0.26687977 0.69581685]
  [0.2248575  0.26602637 0.08408424 0.84938186 0.94730539]
  [0.87901224 0.20191186 0.63780328 0.51041547 0.46684125]]] 


True


In [9]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, '\n\n')
print(d_min, '\n\n')
print(d_mean, '\n\n')

1.9473053949337704 


1.0840842406360371 


1.575872331979131 




In [16]:
f = d.copy()

f[(f > d_min) & (f < d_mean)] = 25
f[(f > d_mean) & (f < d_max)] = 75
f[f == d_mean] = 50
f[f == d_min] = 0
f[f == d_max] = 100

f1 = d.copy()

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] == d_min:
                g1[i][j][k] = 0
            elif d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g1[i][j][k] = 25
            elif d[i][j][k] == d_mean:
                g1[i][j][k] = 50   
            elif d[i][j][k] == d_mean and d[i][j][k] < d_max:
                g1[i][j][k] = 75
            elif d[i][j][k] == d_max:
                g1[i][j][k] = 100
            else:
                g1[i][j][k] = None

print(d, '\n\n')
print(f, '\n\n')
print(f1, '\n\n')

[[[1.78880951 1.55957597 1.66695463 1.52644252 1.68868902]
  [1.53564137 1.37914965 1.70407362 1.12872362 1.8455654 ]
  [1.90476228 1.91983747 1.23117976 1.93933524 1.22597083]]

 [[1.79198097 1.67772611 1.73141591 1.26687977 1.69581685]
  [1.2248575  1.26602637 1.08408424 1.84938186 1.94730539]
  [1.87901224 1.20191186 1.63780328 1.51041547 1.46684125]]] 


[[[ 75.  25.  75.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  25.   0.  75. 100.]
  [ 75.  25.  75.  25.  25.]]] 


[[[1.78880951 1.55957597 1.66695463 1.52644252 1.68868902]
  [1.53564137 1.37914965 1.70407362 1.12872362 1.8455654 ]
  [1.90476228 1.91983747 1.23117976 1.93933524 1.22597083]]

 [[1.79198097 1.67772611 1.73141591 1.26687977 1.69581685]
  [1.2248575  1.26602637 1.08408424 1.84938186 1.94730539]
  [1.87901224 1.20191186 1.63780328 1.51041547 1.46684125]]] 




In [13]:
g = f.copy().astype(str)

g[f == 0] = 'A'
g[f == 25] = 'B'
g[f == 50] = 'C'
g[f == 75] = 'D'
g[f == 100] = 'E'

g1 = d.copy().astype(str)

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] == d_min:
                g1[i][j][k] = 'A'
            elif d[i][j][k] > d_min and d[i][j][k] < d_mean
                g1[i][j][k] = 'B'
            elif d[i][j][k] == d_mean:
                g1[i][j][k] = 'C'   
            elif d[i][j][k] == d_mean and d[i][j][k] < d_max:
                g1[i][j][k] = 'D'
            elif d[i][j][k] == d_max:
                g1[i][j][k] = 'E'
            else:
                g1[i][j][k] = None

print(d, '\n\n')
print(g, '\n\n')
print(g1, '\n\n')

[[[1.78880951 1.55957597 1.66695463 1.52644252 1.68868902]
  [1.53564137 1.37914965 1.70407362 1.12872362 1.8455654 ]
  [1.90476228 1.91983747 1.23117976 1.93933524 1.22597083]]

 [[1.79198097 1.67772611 1.73141591 1.26687977 1.69581685]
  [1.2248575  1.26602637 1.08408424 1.84938186 1.94730539]
  [1.87901224 1.20191186 1.63780328 1.51041547 1.46684125]]] 


[[['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'D']
  ['B' 'B' 'A' 'D' 'E']
  ['D' 'B' 'D' 'B' 'B']]] 


[[['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'D']
  ['B' 'B' 'A' 'D' 'E']
  ['D' 'B' 'D' 'B' 'B']]] 


