In [3]:
import numpy as np

In [4]:
print(np.version.version)

1.16.4


In [127]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))
a1 = np.random.rand(2,3,5)
a2= np.random.randint(1,size=(2,3,5))

# #4. Print a.
print("A is:", a)


# #5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# #Assign the array to variable "b"

b= np.full((5,2,3), 1)
b1 = np.ones((5, 3, 2), dtype = int)





# #6. Print b.

print("B is:", b)
print("B1 is:", b1)

# #7. Do a and b have the same size? How do you prove that in Python code?
equal= np.array_equal(a,b)
print("A&B are :",equal)

equal1= (a.shape==b.shape)
print(equal1)


# #8. Are you able to add a and b? Why or why not?

# since If a.shape != b.shape, they must be broadcastable to a common shape.
#to change shapes use below
# print(a.resize(b.shape))
# print(a+b)
# print(a.size==b.size)
# print(a.shape==b.shape)

# #9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c= b1.T
c1= b.transpose()
c2= np.transpose(b1)
print(c)
print(a.size==c.size)
print(a.shape==c.shape)
# #10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=a+c
# #11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a,'\n')
print(d,'\n')


# #12. Multiply a and c. Assign the result to e.

e= a*c
print("E is:",e,'\n')

# #13. Does e equal to a? Why or why not?

print(np.array_equal(a, e))


# #14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max= d.max()
d_min= d.min()
d_mean= d.mean()

print(d_max)
print(d_min)
print(d_mean)


# #15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f=d.copy()




# """
# #16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
# """






# """
# #17. Print d and f. Do you have your expected f?
# For instance, if your d is:
# array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#         [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#         [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

#        [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#         [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#         [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Your f should be:
# array([[[ 75.,  75.,  75.,  25.,  75.],
#         [ 75.,  75.,  25.,  25.,  25.],
#         [ 75.,  25.,  75.,  75.,  75.]],

#        [[ 25.,  25.,  25.,  25., 100.],
#         [ 75.,  75.,  75.,  75.,  75.],
#         [ 25.,  75.,   0.,  75.,  75.]]])
# """


# """
# #18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],

#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.
# '''
g = f.copy().astype(str)

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] ='B'
            elif d[i][j][k]> d_mean and d[i][j][k] <d_max:
                g[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                g[i][j][k] ='C'
            elif d[i][j][k] == d_min:
                g[i][j][k]='A'
            elif d[i][j][k] == d_max:
                g[i][j][k]='E'
            else:
                g[i][j][k]=0
                
    print(g)
    

A is: [[[0.69454076 0.29690376 0.93244704 0.71224158 0.65093386]
  [0.36295679 0.45174523 0.02579992 0.61550363 0.90884587]
  [0.68827739 0.17271657 0.37402802 0.45066544 0.27119412]]

 [[0.2537533  0.09337453 0.23237989 0.26610859 0.14476066]
  [0.28738982 0.04048597 0.69588117 0.88409397 0.12065459]
  [0.9997121  0.27501174 0.12285269 0.70445934 0.71223094]]]
B is: [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
B1 is: [[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
A&B are : False
False
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
True
True
[[[0.69454076 0.29690376 0.93244704 0.71224158 0.65093386]
  [0.36295679 0.45174523 0.02579992 0.61550363 0.90884587]
  [0.68827739 0.17271657 0.37402802 0.45066544 0.27119412]]

 [[0.2537533  0.09337453 0.23237989 0.26610859 0.14476066]
  [0.28738982 0.04048597 

In [118]:

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] =25
            elif d[i][j][k]> d_mean and d[i][j][k] <d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] =50
            elif d[i][j][k] == d_min:
                f[i][j][k]=0
            elif d[i][j][k] == d_max:
                f[i][j][k]=100
            else:
                f[i][j][k]=0
                
    print(f)
    

[[[ 25.  25.  75.  25. 100.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]
  [  0.  75.  75.  25.  25.]]]
[[[ 25.  25.  75.  25. 100.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]
  [  0.  75.  75.  25.  25.]]]
